name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output: github-contribution-grid-snake.svg

      - name: Push the generated files
        uses: actions/upload-artifact@v2  # Ganti ke v2
        with:
          name: snake-game
          path: github-contribution-grid-snake.svg
